### ISSUE TITLE
Can't add new redirects

### ISSUE THREAD

**Issue by cmhansen26** [venveo/craft-redirect#43] opened 2020-09-16 15:32 UTC
When adding a new redirect, it errors when trying to save and replaces the Destination URL box with an Entry element selector called "Target Element." This shows the correct entry that you had typed in the Destination URL. When you save again, you get another can't save error, and the Destination URL box is back but blank, with the additional error "Destination Url cannot be blank."

**Comment by Mosnar** [comment] 2020-09-20 22:17
I've been having trouble reproducing this error. I remember seeing it a few months ago, but I'm not having much luck getting it to popup now. It'd be a big help if you could provide some information:

1. What version of the plugin are you using?
2. What version of Craft are you using?
3. Are you running Craft in multi-site mode?
4. If you're in multi-site mode, are you trying to save a redirect in a primary or non-primary site?
5. Are you creating a redirect to a page that exists on your site or an external URL?

**Comment by cmhansen26** [comment] 2020-09-21 03:38
@Mosnar for sure! 

1. On 3.0.6 of Redirects plugin.
2. Running Craft Pro 3.5.10.1. 
3. Running multi-site.
4. Saving in primary site.
5. Redirecting to a page on my site. Actually trying to help with a common spelling error for this redirect.

**Comment by cmhansen26** [comment] 2020-11-03 16:40
@Mosnar hey! any luck with this fix yet? I'm running Craft Pro 3.5.14, still having the same issue :/

**Comment by Mosnar** [comment] 2020-11-11 13:51
Sorry for the delay - turns out I'm a dummy and pushed a fix for this months ago that I forgot to release - which is why I was never able to reproduce it locally 🤦 

Fixed in #44

**Closed as completed by Mosnar** 2020-11-11 13:51 UTC

**Comment by cmhansen26** [comment] 2020-11-17 05:01
Well, you're one of the most helpful dummies I know! Thanks for the update, @Mosnar. Working like a charm now!
